### ISSUE TITLE
Objectvie-c 

### ISSUE THREAD

**Issue by rem0t** [KaneCheshire/ShowTime#12]
Hello, how can i use this framework in my objective-c project ? if possible

**Comment by KaneCheshire** [comment]
Good question, not one that I've thought about.

If you add ShowTime as a pod, you should be able to just `@import ShowTime` and then set `ShowTime.enabled`. 

Have you tried anything yourself yet? If so, what have you tried and have you had any errors?

**Comment by rem0t** [comment]
I added the showTime.swift file and make Bridging-Header.h, then I do #import "myPojectName-Swift.h", bud objectvie-c not see public struct ShowTime
![2018-01-15 18 18 33](https://user-images.githubusercontent.com/23454470/34949215-8839ff26-fa20-11e7-862b-0ebadc13b05e.png)

**Comment by KaneCheshire** [comment]
Ahh yes it's likely because it's a struct. I could look at moving it over to a `final class` instead, considering all the properties and functions are `static`.

**Comment by rem0t** [comment]
It would be nice :) if you have time for this

**Comment by KaneCheshire** [comment]
Hey @rem0t, I've just created a PR for this, once the builds have passed I'll merge it in and release 2.1.0 which will have support for Obj-C. Until then if you want to check it out you can point your pod file to `feature/objc-support` and run `pod update` and it should work great :)

**Comment by rem0t** [comment]
HI, ty it's great )
