### ISSUE TITLE
Swift Compiler Error: Type 'UIFontWeight' (aka 'CGFloat') has no member 'bold'

### ISSUE THREAD

**Issue by fungilation** [KaneCheshire/ShowTime#20]
This is compiling for iOS 9.0 as target, on Xcode 9.2. In a React Native (0.53) project. I installed manually by dropping `ShowTime.swift` into my project.

```
Type 'UIFontWeight' (aka 'CGFloat') has no member 'bold'
```
<img width="869" alt="screenshot 2018-03-21 12 22 59" src="https://user-images.githubusercontent.com/3803466/37732573-a96c4982-2d02-11e8-816f-8a07593b5c7c.png">

Solution: https://stackoverflow.com/questions/31771679/uifont-how-to-get-system-thin-font

I can compile by changing the line to end with `weight: UIFontWeightBold`. I don't do Swift development so I'm not going to say whether this is a correct fix for PR.

**Comment by KaneCheshire** [comment]
Hmm that's weird. Do you know which version of Swift it's trying to compile to? It might work if you use the Swift 3 version instead of the Swift 4 version of ShowTime

**Comment by fungilation** [comment]
It's set to Swift 3.2 (I haven't changed it) in the root of my Xcode project > Build Settings. It's a manual install so I just dropped the latest (2.3) version of `ShowTime.swift` into my project.

Everything works great though with my change, so I'm just reporting.

**Comment by KaneCheshire** [comment]
Ah okay, yeah in Swift 4 they changed some of the global variables like`UIFontWeightBold` to be namespaced, but it's not backwards compatible. If you use the Swift 3 version of ShowTime it should still work without any changes needed: 

https://github.com/KaneCheshire/ShowTime/tree/1.0.1

**Comment by fungilation** [comment]
Umm you got it the other way around. My Xcode build settings is set to Swift 3.2, I haven't changed it.

**Comment by KaneCheshire** [comment]
I'm not saying you have, I'm saying you're using the Swift 4 version of ShowTime which won't work if your project is using Swift 3.2, because in Swift 4 `UIFontWeightBold` was changed to `.bold` which is why you have to change it manually back to `UIFontWeightBold`.

The latest version of Showtime (2.3) won't work with Swift 3.2, so you should use version 1.0.1 which I've linked to above.

**Comment by fungilation** [comment]
Ah. I confirm changing Build Settings to Swift 4.0 works with original `.bold` on build. Closing

**Comment by KaneCheshire** [comment]
Awesome thanks for checking!
