### ISSUE TITLE
Support SPM

### ISSUE THREAD

**Issue by KaneCheshire** [KaneCheshire/ShowTime#32]

**Comment by legolasW** [comment]
Really want SPM as well!

**Comment by halonsoluis** [comment]
HI @KaneCheshire, I see some work regarding this in another branch. 
Do we have an ETA?

**Comment by KaneCheshire** [comment]
There's a PR open for this now so not long :)

**Comment by KaneCheshire** [comment]
Merged! You should be able to use SPM now.
