### ISSUE TITLE
iOS 13.4 support

### ISSUE THREAD

**Issue by pacification** [KaneCheshire/ShowTime#34]
Hi! Could you fix some warnings to support latest iOS 13.4? Thanks

**Comment by halonsoluis** [comment]
I guess this can be closed too.
Unless is referring to the example project.

I have noticed that it does not compile with the version of one of the dependencies, but when updating it, some tests fail

**Comment by KaneCheshire** [comment]
I've published 2.5.1 to Cocoapods now
