### ISSUE TITLE
'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.2 — please upgrade to at least 9.0

### ISSUE THREAD

**Issue by stuffmc** [KaneCheshire/ShowTime#48]
This warning shows

`The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.2, but the range of supported deployment target versions is 9.0 to 14.4.99.`

Please upgrade, like https://github.com/wtw-software/UTMConversion/issues/12 did :)

**Comment by atrinh0** [comment]
Resolved in https://github.com/KaneCheshire/ShowTime/pull/46

**Comment by stuffmc** [comment]
Thanks!

**Comment by KaneCheshire** [comment]
I've merged that PR now :)

**Comment by stuffmc** [comment]
Hey @KaneCheshire thanks! But shouldn't we get a new tag for SPM? It could be `2.5.3` but I'd suggest `2.6` since the Deployment target is upped. Your choice.

**Comment by KaneCheshire** [comment]
Yep as soon as that release branch is merged it'll get a new tag :)

**Comment by stuffmc** [comment]
Yeah sorry I wasn't realising you're doing it right like git-flow prescribes it! Great!
