### ISSUE TITLE
`Method Swizzling` on .never

### ISSUE THREAD

**Issue by 0x6d6e** [KaneCheshire/ShowTime#8]
Hello,
This is more of an observation from our team than a bug but
```
  public static var enabled: ShowTime.Enabled = .never {
    didSet {
      UIWindow.swizzle()
    }
  }
```
 essentially swizzles an event irrespective of .enabled value even if its `never`. Shouldn't ` UIWindow.swizzle()` only on `.debugOnly` and `.always`?

**Comment by KaneCheshire** [comment]
Hey!

Ah yes that's a good point. I think it should be easy to fix but not sure it's too much of an issue because the default value is already `.never`. Happy to fix though if it does cause problems!

**Comment by 0x6d6e** [comment]
@KaneCheshire No issues at all. Like I said more of an observation than an issue or bug. Looking forward to using this for our demos 👍 . I'm closing this thread. Thx
